eureka-credentials:
  username: admin
  password: admin
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka-credentials.username}:${eureka-credentials.password}@0.0.0.0:8761/eureka/

spring:
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: create-drop
    show-sql: true

  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/smartisdb
    username: postgres
    password: postgres   

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'                    
